standard_library = {
    "Built-in Functions": [
        "abs",
        "aiter",
        "all",
        "anext",
        "any",
        "ascii",
        "bin",
        "bool",
        "breakpoint",
        "callable",
        "chr",
        "classmethod",
        "compile",
        "complex",
        "delattr",
        "dir",
        "divmod",
        "enumerate",
        "eval",
        "exec",
        "filter",
        "float",
        "format",
        "getattr",
        "globals",
        "hasattr",
        "hash",
        "help",
        "hex",
        "id",
        "input",
        "int",
        "isinstance",
        "issubclass",
        "iter",
        "len",
        "locals",
        "map",
        "max",
        "min",
        "next",
        "object",
        "oct",
        "open",
        "ord",
        "pow",
        "print",
        "property",
        "repr",
        "reversed",
        "round",
        "setattr",
        "slice",
        "sorted",
        "staticmethod",
        "sum",
        "super",
        "type",
        "vars",
        "__import__"
    ],
    "Built-in Constants": [
        "False",
        "True",
        "None",
        "NotImplemented",
        "Ellipsis",
        "__debug__"
    ],
    "Constants added by the site module": [],
    "Built-in Types": [
        "Truth Value Testing",
        "Boolean Operations — and, or, not",
        "Comparisons",
        "Numeric Types — int, float, complex",
        "Boolean Type - bool",
        "Iterator Types",
        "Sequence Types — list, tuple, range",
        "Text Sequence Type — str",
        "Binary Sequence Types — bytes, bytearray, memoryview",
        "Set Types — set, frozenset",
        "Mapping Types — dict",
        "Context Manager Types",
        "Type Annotation Types — Generic Alias, Union",
        "Other Built-in Types",
        "Special Attributes",
        "Integer string conversion length limitation"
    ],
    "Built-in Exceptions": [
        "Exception context",
        "Inheriting from built-in exceptions",
        "Base classes",
        "Concrete exceptions",
        "Warnings",
        "Exception groups",
        "Exception hierarchy"
    ],
    "Text Processing Services": [
        "string — Common string operations",
        "re — Regular expression operations",
        "difflib — Helpers for computing deltas",
        "textwrap — Text wrapping and filling",
        "unicodedata — Unicode Database",
        "stringprep — Internet String Preparation",
        "readline — GNU readline interface",
        "rlcompleter — Completion function for GNU readline"
    ],
    "Binary Data Services": [
        "struct — Interpret bytes as packed binary data",
        "codecs — Codec registry and base classes",
        "Data Types",
        "datetime — Basic date and time types",
        "zoneinfo — IANA time zone support",
        "calendar — General calendar-related functions",
        "collections — Container datatypes",
        "collections.abc — Abstract Base Classes for Containers",
        "heapq — Heap queue algorithm",
        "bisect — Array bisection algorithm",
        "array — Efficient arrays of numeric values",
        "weakref — Weak references",
        "types — Dynamic type creation and names for built-in types",
        "copy — Shallow and deep copy operations",
        "pprint — Data pretty printer",
        "reprlib — Alternate repr() implementation",
        "enum — Support for enumerations",
        "graphlib — Functionality to operate with graph-like structures"
    ],
    "Numeric and Mathematical Modules": [
        "numbers — Numeric abstract base classes",
        "math — Mathematical functions",
        "cmath — Mathematical functions for complex numbers",
        "decimal — Decimal fixed-point and floating-point arithmetic",
        "fractions — Rational numbers",
        "random — Generate pseudo-random numbers",
        "statistics — Mathematical statistics functions"
    ],
    "Functional Programming Modules": [
        "itertools — Functions creating iterators for efficient looping",
        "functools — Higher-order functions and operations on callable objects",
        "operator — Standard operators as functions"
    ],
    "File and Directory Access": [
        "pathlib — Object-oriented filesystem paths",
        "os.path — Common pathname manipulations",
        "fileinput — Iterate over lines from multiple input streams",
        "stat — Interpreting stat() results",
        "filecmp — File and Directory Comparisons",
        "tempfile — Generate temporary files and directories",
        "glob — Unix style pathname pattern expansion",
        "fnmatch — Unix filename pattern matching",
        "linecache — Random access to text lines",
        "shutil — High-level file operations"
    ],
    "Data Persistence": [
        "pickle — Python object serialization",
        "copyreg — Register pickle support functions",
        "shelve — Python object persistence",
        "marshal — Internal Python object serialization",
        "dbm — Interfaces to Unix “databases”",
        "sqlite3 — DB-API 2.0 interface for SQLite databases"
    ],
    "Data Compression and Archiving": [
        "zlib — Compression compatible with gzip",
        "gzip — Support for gzip files",
        "bz2 — Support for bzip2 compression",
        "lzma — Compression using the LZMA algorithm",
        "zipfile — Work with ZIP archives",
        "tarfile — Read and write tar archive files"
    ],
    "File Formats": [
        "csv — CSV File Reading and Writing",
        "configparser — Configuration file parser",
        "tomllib — Parse TOML files",
        "netrc — netrc file processing",
        "plistlib — Generate and parse Apple .plist files"
    ],
    "Cryptographic Services": [
        "hashlib — Secure hashes and message digests",
        "hmac — Keyed-Hashing for Message Authentication",
        "secrets — Generate secure random numbers for managing secrets"
    ],
    "Generic Operating System Services": [
        "os — Miscellaneous operating system interfaces",
        "io — Core tools for working with streams",
        "time — Time access and conversions",
        "argparse — Parser for command-line options, arguments and subcommands",
        "logging — Logging facility for Python",
        "logging.config — Logging configuration",
        "logging.handlers — Logging handlers",
        "getpass — Portable password input",
        "curses — Terminal handling for character-cell displays",
        "curses.textpad — Text input widget for curses programs",
        "curses.ascii — Utilities for ASCII characters",
        "curses.panel — A panel stack extension for curses",
        "platform — Access to underlying platform’s identifying data",
        "errno — Standard errno system symbols",
        "ctypes — A foreign function library for Python"
    ],
    "Concurrent Execution": [
        "threading — Thread-based parallelism",
        "multiprocessing — Process-based parallelism",
        "multiprocessing.shared_memory — Shared memory for direct access across processes",
        "concurrent.futures — Launching parallel tasks",
        "subprocess — Subprocess management",
        "sched — Event scheduler",
        "queue — A synchronized queue class",
        "contextvars — Context Variables",
        "_thread — Low-level threading API"
    ],
    "Networking and Interprocess Communication": [
        "asyncio — Asynchronous I/O",
        "socket — Low-level networking interface",
        "ssl — TLS/SSL wrapper for socket objects",
        "select — Waiting for I/O completion",
        "selectors — High-level I/O multiplexing",
        "signal — Set handlers for asynchronous events",
        "mmap — Memory-mapped file support"
    ],
    "Internet Data Handling": [
        "email — An email and MIME handling package",
        "json — JSON encoder and decoder",
        "mailbox — Manipulate mailboxes in various formats",
        "mimetypes — Map filenames to MIME types",
        "base64 — Base16, Base32, Base64, Base85 Data Encodings",
        "binascii — Convert between binary and ASCII",
        "quopri — Encode and decode MIME quoted-printable data"
    ],
    "Structured Markup Processing Tools": [
        "html — HyperText Markup Language support",
        "html.parser — Simple HTML and XHTML parser",
        "html.entities — Definitions of HTML general entities"
    ],
    "XML Processing Modules": [
        "xml.etree.ElementTree — The ElementTree XML API",
        "xml.dom — The Document Object Model API",
        "xml.dom.minidom — Minimal DOM implementation",
        "xml.dom.pulldom — Support for building partial DOM trees",
        "xml.sax — Support for SAX2 parsers",
        "xml.sax.handler — Base classes for SAX handlers",
        "xml.sax.saxutils — SAX Utilities",
        "xml.sax.xmlreader — Interface for XML parsers",
        "xml.parsers.expat — Fast XML parsing using Expat"
    ],
    "Internet Protocols and Support": [
        "webbrowser — Convenient web-browser controller",
        "wsgiref — WSGI Utilities and Reference Implementation",
        "urllib — URL handling modules",
        "urllib.request — Extensible library for opening URLs",
        "urllib.response — Response classes used by urllib",
        "urllib.parse — Parse URLs into components",
        "urllib.error — Exception classes raised by urllib.request",
        "urllib.robotparser — Parser for robots.txt",
        "http — HTTP modules",
        "http.client — HTTP protocol client",
        "ftplib — FTP protocol client",
        "poplib — POP3 protocol client",
        "imaplib — IM